### ISSUE TITLE
Compilation problems for Intel MPI

### ISSUE THREAD

**Issue by paulfons** [gudasergey/fdmnes#1]
Hi,
  I am interested in compiling the Intel MPI version of fdmnes and I have had some troubles doing so although the program linked without errors.  I have downloaded scotch 6.0.4, metis-5.1.0, and MUMPS 5.0.1 in addition to fdmnes from github.  I then compiled MUMPS using the Makefile.INTEL.PAR and after compilation the example programs work fine (e.g. mpiexec.hydra -np 2 ./zsimpletest < input_simpletest_cmplx) gives the correct answer.  For metis-5.1.0 I left the size of the IDXTYPEWIDTH constant at 32 bits and compiled using make without errors.  I also compiled scotch 6.0.4 using after making a symbolic link to Makefile.inc/Makefile.inc.x86-64_pc_linux2.icc to Makefile.inc for compilation.  The test suite in the check directory worked fine.  I moved a copy of all of the libraries generated to the "bib" directory in fdmnes in preparation for compiling fdmnes.  After changing to the prog directory of fdmnes, I then moved the sources mpi.h, not_mpi.f90, sub_util.f, and mat_solve_gaussian.f90 to a "not used subdirectory" and then ran make after pointing the "BIB" environment variable in the makefile to the directory with libraries from scotch, metis, and MUMPS. I also changed FC to "mpiifort".  The compilation proceeded without error and I ended up with a ELF 64-bit LSB executable called "fdmnes".  Running this via mpiexec.hydra -n 2 ./fdmnes causes duplicated output and the program stating that it is running in serial form with a MPI error message at the end ERROR in MPI_ALLREDUCE, DATATYPE=  1275069467.

Can you offer me any suggestions as to what to try next.  It is not clear to me what to try now without digging through the source code.  Why, for example, is the code running sequentially even though I followed the instructions in the fdmnes manual for making the mpi version?

Alternatively, if you have a binary for the MPI version of fdmnes for Intel that you could share, this would be a solution as well.

Thanks for your help.

Best wishes,
                   Paul Fons

**Comment by gudasergey** [comment]
```
Dear Paul!
Why did you not download binary parallel fdmnes with intel mpi from
github repository?
You can find it in every release 
https://github.com/gudasergey/fdmnes/releases
by the name "parallel_fdmnes.tar.gz".

Sincerely yours,
Sergey
```

**Comment by paulfons** [comment]
Hi Sergey,

  Thank you for stating what I should have seen myself.  I actually spent a lot of time with the cnrs version (whose documentation on the MUMPS extensions is quite poor) and then only noticed your github fork with a google search to the sources (https://github.com/gudasergey/fdmnes) and the binary does not show up without looking at the releases link (which I didn’t think to look at as I was focusing on compiling from source).  I am grateful for the binary as it will let me get to work right away, but I don’t understand why the version I compiled according to the procedure below doesn’t recognize the existence of a MPI environment.  I can see that the code I compiled doesn’t recognize the existence of a MPI environment, but adding a couple of print statements near the initial determination of a sequential or parallel run.  I attached the relevant lines from main.f90 and the top of the output when run below.  As you can see, the number of MPI nodes is being returned as 1, even when it is 2 (or any other larger value) .   Admittedly, solving the problem is not so important now with a working binary, but I would like to understand what is going wrong.  Do you have a makefile that I could look at if you don’t have time to troubleshoot my problem?

Best wishes,
            Paul

! mpinodes0 is the total number of nodes for parallel computing
! mpinodes is the number of nodes for the energy loop for parallel computing
  call MPI_Init( mpierr )
  write(_,_) ' The mpierr value returned from MPI_Init is ',mpierr
  call MPI_Comm_Size(MPI_COMM_WORLD,mpinodes0,mpierr)
  call MPI_Comm_Rank(MPI_COMM_WORLD,mpirank0,mpierr)

 write(_,_) 'The number of MPI nodes is: ‘,mpinodes0
 write(_,_) 'The MPI rank is: ',mpirank0

running this gives

~/fdmnes>mpiexec.hydra -n 2 ./fdmnes
  The mpierr value returned from MPI_Init is            0
 The number of MPI nodes is:            1
 The MPI rank is:            0
   FDMNES II program, Revision 12 February 2016  
   Date = 09 03 2016  
   Time = 08 h 59 mn 00 s  
  The mpierr value returned from MPI_Init is            0
 The number of MPI nodes is:            1
 The MPI rank is:            0
   FDMNES II program, Revision 12 February 2016  
   Date = 09 03 2016  
   Time = 08 h 59 mn 00 s        

> On Mar 9, 2016, at 3:26 AM, Sergey Guda notifications@github.com wrote:
> 
> Dear Paul!
> Why did you not download binary parallel fdmnes with intel mpi from
> github repository?
> You can find it in every release 
> https://github.com/gudasergey/fdmnes/releases
> by the name "parallel_fdmnes.tar.gz".
> 
> Sincerely yours,
> Sergey
> 
> 08.03.2016 10:44, paulfons пишет:
> 
> Hi,
> I am interested in compiling the Intel MPI version of fdmnes and
> I have had some troubles doing so although the program linked
> without errors. I have downloaded scotch 6.0.4, metis-5.1.0, and
> MUMPS 5.0.1 in addition to fdmnes from github. I then compiled
> MUMPS using the Makefile.INTEL.PAR and after compilation the
> example programs work fine (e.g. mpiexec.hydra -np 2
> ./zsimpletest < input_simpletest_cmplx) gives the correct
> answer. For metis-5.1.0 I left the size of the IDXTYPEWIDTH
> constant at 32 bits and compiled using make without errors. I
> also compiled scotch 6.0.4 using after making a symbolic link to
> Makefile.inc/Makefile.inc.x86-64_pc_linux2.icc to Makefile.inc
> for compilation. The test suite in the check directory worked
> fine. I moved a copy of all of the libraries generated to the
> "bib" directory in fdmnes in preparation for compiling fdmnes.
> After changing to the prog directory of fdmnes, I then moved the
> sources mpi.h, not_mpi.f90, sub_util.f, and mat_s olve_gau
> ssian.f90 to a "not used subdirectory" and then ran make after
> pointing the "BIB" environment variable in the makefile to the
> directory with libraries from scotch, metis, and MUMPS. I also
> changed FC to "mpiifort". The compilation proceeded without
> error and I ended up with a ELF 64-bit LSB executable called
> "fdmnes". Running this via mpiexec.hydra -n 2 ./fdmnes causes
> duplicated output and the program stating that it is running in
> serial form with a MPI error message at the end ERROR in
> MPI_ALLREDUCE, DATATYPE= 1275069467.
> Can you offer me any suggestions as to what to try next. It is
> not clear to me what to try now without digging through the
> source code. Why, for example, is the code running sequentially
> even though I followed the instructions in the fdmnes manual for
> making the mpi version?
> Alternatively, if you have a binary for the MPI version of
> fdmnes for Intel that you could share, this would be a solution
> as well.
> Thanks for your help.
> Best wishes,
> Paul Fons
> —
> Reply to this email directly or view it
> on GitHub.
> —
> Reply to this email directly or view it on GitHub.

Dr. Paul Fons
Chief Researcher
Systematic Materials Design Group
Nanoelectronics Research Institute
National Institute for Advanced Industrial Science & Technology, METI

AIST Central 5, Higashi 1-1-1Tsukuba, Ibaraki JAPAN 305-8565

tel. +81-298-61-5636fax. +81-298-61-2939

email: paul-fons@aist.go.jp

The following lines are in a Japanese font

〒305-8565 茨城県つくば市つくば東 1-1-1 中央第５
国立研究開発法人産業技術総合研究所　
ナノエレクトロニクス研究部門
システマティックマテリアルズデサイングループ
上級主任研究員
ポール・フォンス

**Comment by gudasergey** [comment]
Dear Paul!
I attach to the letter the makefile, that I use to build parallel fdmnes.
FDMNES doesn't use SCOTCH. It uses only METIS.
Check, that mpirun (or mpiexec.hydra) command belong to the same MPI 
installation, that you use for compilation of FDMNES. Also check the 
dynamic libraries which are linked to the executable, when you run it 
(use "ldd <exe>" command).

Sincerely yours,
Sergey

FORTRAN=mpiifort

OPTS=-O2 -g1 -traceback -zero -heap-arrays

# Solvers: mat_solve_gaussian - gaussian slow solver,

# mat_solve_mumps - mumps parallel solver

LINEAR_SOLVER=mat_solve_mumps
EXECUTABLE_NAME=fdmnes_mpi_linux64

#full path to libmetis.a 
METIS_DIR=/home/sguda/fdmnes/LIB64/parmetis
METIS=$(METIS_DIR)/libparmetis.a $(METIS_DIR)/libmetis.a

MUMPS_DIR=/home/sguda/fdmnes/LIB64/MUMPS

MUMPS_INCLUDE_DIR=-I$(MUMPS_DIR)/include

MUMPS_LIBS=$(MUMPS_DIR)/lib/libdmumps.a \
    $(MUMPS_DIR)/lib/libzmumps.a \
    $(MUMPS_DIR)/lib/libmumps_common.a \
    $(MUMPS_DIR)/lib/libpord.a \
    $(METIS)  \
    -L/opt/intel/composer_xe_2015.2.164/mkl/lib/intel64 -lmkl_blacs_intelmpi_lp64 \
    -lmkl_scalapack_lp64 -mkl=sequential -static-intel

# Make file for the fdmnes package

include make.inc_intel_mpi

ifeq ($(LINEAR_SOLVER), mat_solve_mumps)
    LIBS = $(MUMPS_LIBS)  
else
    LIBS = $(LAPACK)
    ifneq ($(LINEAR_SOLVER), mat_solve_gaussian)
        $(error Unknown value for LINEAR_SOLVER variable)
    endif
endif

#on some 32-bit systems fdmnes suspends in sub_util.f. Replace it by linking with lapack and blas
FDMNES =  clemf0.o coabs.o convolution.o dirac.o fdm.o fprime.o general.o sphere.o \
                    lecture.o mat.o metric.o minim.o  potential.o scf.o selec.o \
                    spgroup.o tab_data.o tddft.o tensor.o optic.o \
                    $(LINEAR_SOLVER).o

all: FDMNES_MAIN $(FDMNES)
    $(info You are using $(LINEAR_SOLVER) solver)
    $(FORTRAN) main.o $(FDMNES) $(LIBS) -o $(EXECUTABLE_NAME)

FDMNES_MAIN:
    $(FORTRAN) $(MUMPS_INCLUDE_DIR) $(OPTS) main.f90 -c -o main.o

clean: 
    rm -f *.o *.mod

%.o: %.f
    $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@

%.o: %.f90 FDMNES_MAIN
    $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@

%.o: %.c
    $(C) $(COPTS) -c $< -o $@

%.o: %.cpp
    $(C) $(COPTS) -c $< -o $@

**Comment by paulfons** [comment]
Thanks Sergey,

  I will give a try compiling it myself.  In the meantime I am already using the compiled version.  Thank you for your efforts.

Best wishes,
            Paul

> On Mar 9, 2016, at 7:57 PM, Sergey Guda notifications@github.com wrote:
> 
> Dear Paul!
> I attach to the letter the makefile, that I use to build parallel fdmnes.
> FDMNES doesn't use SCOTCH. It uses only METIS.
> Check, that mpirun (or mpiexec.hydra) command belong to the same MPI 
> installation, that you use for compilation of FDMNES. Also check the 
> dynamic libraries which are linked to the executable, when you run it 
> (use "ldd <exe>" command).
> 
> Sincerely yours,
> Sergey
> 
> FORTRAN=mpiifort
> 
> OPTS=-O2 -g1 -traceback -zero -heap-arrays
> 
> # Solvers: mat_solve_gaussian - gaussian slow solver,
> 
> # mat_solve_mumps - mumps parallel solver
> 
> LINEAR_SOLVER=mat_solve_mumps
> EXECUTABLE_NAME=fdmnes_mpi_linux64
> 
> #full path to libmetis.a 
> METIS_DIR=/home/sguda/fdmnes/LIB64/parmetis
> METIS=$(METIS_DIR)/libparmetis.a $(METIS_DIR)/libmetis.a
> 
> MUMPS_DIR=/home/sguda/fdmnes/LIB64/MUMPS
> 
> MUMPS_INCLUDE_DIR=-I$(MUMPS_DIR)/include
> 
> MUMPS_LIBS=$(MUMPS_DIR)/lib/libdmumps.a \
> $(MUMPS_DIR)/lib/libzmumps.a \
> $(MUMPS_DIR)/lib/libmumps_common.a \
> $(MUMPS_DIR)/lib/libpord.a \
> $(METIS) \
> -L/opt/intel/composer_xe_2015.2.164/mkl/lib/intel64 -lmkl_blacs_intelmpi_lp64 \
> -lmkl_scalapack_lp64 -mkl=sequential -static-intel
> 
> # Make file for the fdmnes package
> 
> include make.inc_intel_mpi 
> 
> ifeq ($(LINEAR_SOLVER), mat_solve_mumps) 
> LIBS = $(MUMPS_LIBS) 
> else 
> LIBS = $(LAPACK) 
> ifneq ($(LINEAR_SOLVER), mat_solve_gaussian) 
> $(error Unknown value for LINEAR_SOLVER variable) 
> endif 
> endif 
> 
> #on some 32-bit systems fdmnes suspends in sub_util.f. Replace it by linking with lapack and blas 
> FDMNES = clemf0.o coabs.o convolution.o dirac.o fdm.o fprime.o general.o sphere.o \ 
> lecture.o mat.o metric.o minim.o potential.o scf.o selec.o \ 
> spgroup.o tab_data.o tddft.o tensor.o optic.o \ 
> $(LINEAR_SOLVER).o 
> 
> all: FDMNES_MAIN $(FDMNES) 
> $(info You are using $(LINEAR_SOLVER) solver) 
> $(FORTRAN) main.o $(FDMNES) $(LIBS) -o $(EXECUTABLE_NAME) 
> 
> FDMNES_MAIN: 
> $(FORTRAN) $(MUMPS_INCLUDE_DIR) $(OPTS) main.f90 -c -o main.o 
> 
> clean: 
> rm -f *.o *.mod 
> 
> %.o: %.f 
> $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@ 
> 
> %.o: %.f90 FDMNES_MAIN 
> $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@ 
> 
> %.o: %.c 
> $(C) $(COPTS) -c $< -o $@ 
> 
> %.o: %.cpp 
> $(C) $(COPTS) -c $< -o $@ 
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/gudasergey/fdmnes/issues/1#issuecomment-194240889.

Dr. Paul Fons
Chief Researcher
Systematic Materials Design Group
Nanoelectronics Research Institute
National Institute for Advanced Industrial Science & Technology, METI

AIST Central 5, Higashi 1-1-1Tsukuba, Ibaraki JAPAN 305-8565

tel. +81-298-61-5636fax. +81-298-61-2939

email: paul-fons@aist.go.jp mailto:paul-fons@aist.go.jp

The following lines are in a Japanese font

〒305-8565 茨城県つくば市つくば東 1-1-1 中央第５
国立研究開発法人産業技術総合研究所　
ナノエレクトロニクス研究部門
システマティックマテリアルズデサイングループ
上級主任研究員
ポール・フォンス

**Comment by paulfons** [comment]
Hi Sergey,

  A quick question … I noticed that in the makefile you sent there is a line

> On Mar 9, 2016, at 7:57 PM, Sergey Guda notifications@github.com wrote:
> 
> include make.inc_intel_mpi 

It is my impression that this file is missing in the mail.  Am I correct?

Best wishes,
            Paul

**Comment by gudasergey** [comment]
I sent two different files (github unites it in one):

File make.inc_intel_mpi:

FORTRAN=mpiifort

OPTS=-O2 -g1 -traceback -zero -heap-arrays

# Solvers: mat_solve_gaussian - gaussian slow solver,

# mat_solve_mumps - mumps parallel solver

LINEAR_SOLVER=mat_solve_mumps
EXECUTABLE_NAME=fdmnes_mpi_linux64

#full path to libmetis.a
METIS_DIR=/home/sguda/fdmnes/LIB64/parmetis
METIS=$(METIS_DIR)/libparmetis.a $(METIS_DIR)/libmetis.a

MUMPS_DIR=/home/sguda/fdmnes/LIB64/MUMPS

MUMPS_INCLUDE_DIR=-I$(MUMPS_DIR)/include

MUMPS_LIBS=$(MUMPS_DIR)/lib/libdmumps.a \
     $(MUMPS_DIR)/lib/libzmumps.a \
     $(MUMPS_DIR)/lib/libmumps_common.a \
     $(MUMPS_DIR)/lib/libpord.a \
     $(METIS)  \
     -L/opt/intel/composer_xe_2015.2.164/mkl/lib/intel64 
-lmkl_blacs_intelmpi_lp64 \
     -lmkl_scalapack_lp64 -mkl=sequential -static-intel

and file Makefile:

# Make file for the fdmnes package

include make.inc_intel_mpi

ifeq ($(LINEAR_SOLVER), mat_solve_mumps)
     LIBS = $(MUMPS_LIBS)
else
     LIBS = $(LAPACK)
     ifneq ($(LINEAR_SOLVER), mat_solve_gaussian)
         $(error Unknown value for LINEAR_SOLVER variable)
     endif
endif

#on some 32-bit systems fdmnes suspends in sub_util.f. Replace it by 
linking with lapack and blas
FDMNES =  clemf0.o coabs.o convolution.o dirac.o fdm.o fprime.o 
general.o sphere.o \
                     lecture.o mat.o metric.o minim.o  potential.o scf.o 
selec.o \
                     spgroup.o tab_data.o tddft.o tensor.o optic.o \
                     $(LINEAR_SOLVER).o

all: FDMNES_MAIN $(FDMNES)
     $(info You are using $(LINEAR_SOLVER) solver)
     $(FORTRAN) main.o $(FDMNES) $(LIBS) -o $(EXECUTABLE_NAME)

FDMNES_MAIN:
     $(FORTRAN) $(MUMPS_INCLUDE_DIR) $(OPTS) main.f90 -c -o main.o

clean:
     rm -f *.o *.mod

%.o: %.f
     $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@

%.o: %.f90 FDMNES_MAIN
     $(FORTRAN) $(OPTS) $(MUMPS_INCLUDE_DIR) -c $< -o $@

%.o: %.c
     $(C) $(COPTS) -c $< -o $@

%.o: %.cpp
     $(C) $(COPTS) -c $< -o $@
