### ISSUE TITLE
FDMNES intensity

### ISSUE THREAD

**Issue by kaifengZheng** [gudasergey/fdmnes#11]
Dear professor Guda
I am Kaifeng Zheng, a material science PhD student at Stony Brook University, US. I used FDMNES a lot to calculate XANES. But recently, I encountered a problem in my project. I calculated a bunch of XANES for different sizes and shapes of Pt nanoparticles, but the resulting FDMNES spectra have different Intensity scales, as shown below. I don't know what the correct method is to normalize those spectra and make them comparable to experimental data. Could you give me a hand?
![image](https://github.com/gudasergey/fdmnes/assets/48105165/b54f0c73-e701-44fa-8833-228d33838e86)

Best,
Kaifeng ZHeng

**Comment by lavakyan** [comment]
I would recommend to divide by a number of atoms in the nanoparticle. Of course, it is in the case if all atoms in nanoparticles were counted as absorbers.

**Comment by kaifengZheng** [comment]
> I would recommend to divide by a number of atoms in the nanoparticle. Of course, it is in the case if all atoms in nanoparticles were counted as absorbers.

Dear professor Avakyan,
Thank you very much for the quick response! Sorry I didn't explain the spectra. But you are right; those spectra are particle-averaged and convoluted.  I took the geometry(point group) check functionality in FDMNES by putting Z_absorber using atomic number(78). I think FDMNES will calculate average spectra automatically, correct? But I wonder why we need to further divide the number of atoms in the nanoparticle, as you suggested.  

Best,
Kaifeng Zheng

**Comment by lavakyan** [comment]
You probably right about the averaging. I usually do manual summation, so that was my advise. 

In your case it is probably  that spectra was calculated only for the first atom in the list. Please consult the FDMNES manual. 

A few quotes from manual:
* "By default and in the absence of the keyword "absorber", the absorbing atom chemical specie corresponds to the first atom in the list."
* "If one wants to get the signal coming from each atom one has to add the keyword: **Allsite**"

We need help from someone  (@gudasergey ?)  about Z_absorber keyword. It is new for me.

So, I'd recommend to check if *allsite* will give results different from the *Z_absorber*

**Comment by kaifengZheng** [comment]
Thanks a lot. I will check that and compare Z_absorber with manual averaging. I'm trying to understand what causes the intensity difference and how to normalize the spectra correctly. To this end, it would be great if I could also get help from others. Do you have any suggestions on who I should ask?
![image](https://github.com/gudasergey/fdmnes/assets/48105165/fb0dd558-a7a2-4146-871c-f22eee6520b1)
Description of Z_absorber in the manual:
![image](https://github.com/gudasergey/fdmnes/assets/48105165/4978e7b1-5e27-424f-acfd-24ae24676462)

**Comment by kaifengZheng** [comment]
Dear professor Avakyan,
You are right. All the calculations should divide the number of atoms in the particle. Now, the spectra are more consistent 
![image](https://github.com/gudasergey/fdmnes/assets/48105165/2a833b45-93c7-44c8-b1da-22c2b12cb371)

Thanks a lot!
Kaifeng Zheng

**Comment by kaifengZheng** [comment]
Dear professor Avakyan,
I have one more question. What is the final convolution spectrum if we have multiple absorbers in the list? I think we can get only one _conv file. Is the final convoluted spectrum calculated by adding all site spectra together?
Best,
Kaifeng Zheng
