### ISSUE TITLE
Windows executable closes - no output

### ISSUE THREAD

**Issue by mwschaefer** [gudasergey/fdmnes#2]
I just installed fdmnes on a new computer running Windows 10. I actually downloaded the package from the link on neel.cnrs.fr. The fdmfile.txt, spacegroup.txt, and xsect.dat files are in the same directory as the executable, and I have not edited them from the default. The fdmnes program runs briefly, then the window closes. There is no fdmnes_err.txt file created, or any other file either. I'm not sure what to try at this point.

**Comment by gudasergey** [comment]
I just unpack fdmnes fdmnes package on Windows 10 (64 bit) and successfully run the executables fdmnes_win32.exe and fdmnes_win64.exe. They work fine, print output to command window and generate output files in Sim/Test_stand folder. Everything seems alright.
Does the default fdmnes test work on you computer?

**Comment by mwschaefer** [comment]
Yes, I think it does!  I did not know to look in the Sim/Test_stand folder.  I see three new files: Cu.txt, Cu_bav.txt, and Cu_conv.txt. This is correct?

**Comment by gudasergey** [comment]
Yes. It is correct.

**Comment by mwschaefer** [comment]
Great! Thanks very much! :)
