### ISSUE TITLE
17-July-2016 crash of MPI version using mp

### ISSUE THREAD

**Issue by paulfons** [gudasergey/fdmnes#3]
Using the input file attached for GeTe, running FDMNES using the command "HOST_NUM_FOR_MUMPS=4 ../../..//mpirun_fdmnes -np 24" on a 24 core system results in a fortran allocation error, namely

forrtl: severe (151): allocatable array is already allocated

The error does not occur when the fdmx keyword is omitted implying that the input to FDMNES is at least adequate to compute the XANES spectra without it.  The error would appear to be a memory allocation error perhaps within the MPI loop.

Thanks for your help.

Best wishes,
                       Paul

[fdmnes_error.txt](https://github.com/gudasergey/fdmnes/files/441705/fdmnes_error.txt)
[fdmnes_input.txt](https://github.com/gudasergey/fdmnes/files/441706/fdmnes_input.txt)

**Comment by xishibo** [comment]
Hi Paulfons,

I have had the same problem at the beginning.  
I'd like to share with you how to solve this problem.
1, Open the source code fdm.f90, search "if( i_range > 1 ) deallocate( drho_self, lmaxa, nlmsa, Statedens, Statedens_i )".
2, Replace "if( i_range > 1 ) deallocate( drho_self, lmaxa, nlmsa, Statedens, Statedens_i )" with "if( i_range > 1 ) deallocate( drho_self, lmaxa, nlmsa, Statedens, Statedens_i, sec_atom)". That is, we just insert "sec_atom" to the function deallocate.
3, Recompile the code.

Then it will work smoothly.

Best regards.
Shibo@SSLS

**Comment by gudasergey** [comment]
Check the last release 2016_09_01
