### ISSUE TITLE
Error in general.f90?

### ISSUE THREAD

**Issue by TheSidi** [gudasergey/fdmnes#4]
Great job!
Unfortunately, It seems that on compiling I get an syntax error in general.f90

_general.f90:7449:58:
               if( a * sin( Angle ) + b * cos( Angle ) < c == Below ) cycle_

replacing "==" with ".eqv." seems to resolve the error. However, not sure if this is correct.
Completely new to this subject.

**Comment by gudasergey** [comment]
The standard ( ftp://ftp.nag.co.uk/sc22wg5/N001-N1100/N692.pdf   page 72)  says that "==" and ".EQ." are the same and can be used in Fortran90.
May be you use flags to treat *.f90 as fortran 77 in your compiler?

**Comment by gudasergey** [comment]
Thank you, very much. This is correct.

**Comment by TheSidi** [comment]
Great, thank you.
