### ISSUE TITLE
[build] 2018_06_21 is missing some files

### ISSUE THREAD

**Issue by woutdenolf** [gudasergey/fdmnes#6]
The latest build is missing xsect.dat and spacegroup.txt:
http://neel.cnrs.fr/IMG/zip/fdmnes_2018_06_21.zip

**Comment by gudasergey** [comment]
They are no longer needed

**Comment by woutdenolf** [comment]
Ok thanks. I noticed because I was using a python wrapper of fdmnes which relies on spacegroup.txt (https://github.com/tinaw/pyFDMNES). I added the file to that project's resources.
