### ISSUE TITLE
Unexpected behavior in parallel version

### ISSUE THREAD

**Issue by carichte** [gudasergey/fdmnes#7]
Hi,

I can't manage to get anything reasonable from the parallel binaries.

-  if I run just the binary, I have one process consuming all the compute power of the system (e.g. 1600% in my case)
- if I run `mpirun -np 1 fdmnes` I have the same result
- if I run `mpirun -np N fdmnes` N processes are spawned each taking 1/N of the total CPU power.

In all cases, the runtime is longer compared to that of a win32 binary run via wine

the makefile i use:

```
# Makefile to compile FDMNES with call to MUMPS, LAPACK and BLAS libraries, for sequential calculations
# MUMPS comes with associated other libraries.
# Works with the gfortran Linux Compiler (for other compiler change the FC command)

FC = mpif90
OPTLVL = 3

EXEC = ../fdmnes

# For intel compiler, it seems that probems at execution are avoided when compiling
# sphere.f90 with O1 option and the other routines with O2 option.

BIBDIR = /usr/lib

INCDIR = /usr/lib/x86_64-linux-gnu/openmpi/include
INCDIR_MUMPS = /usr/include

FFLAGS = -c  -O$(OPTLVL) -I$(INCDIR) -I$(INCDIR_MUMPS) -I/usr/lib/x86_64-linux-gnu

OBJ = main.o clemf0.o coabs.o convolution.o diffraction.o dirac.o fdm.o fdmx.o fprime.o fprime_data.o general.o lecture.o mat.o metric.o \
      minim.o optic.o potential.o selec.o scf.o spgroup.o sphere.o tab_data.o tddft.o tensor.o \
      mat_solve_mumps.o

all: $(EXEC)

#$(EXEC): $(OBJ)
#       $(FC) -o $@ $^  -L$(BIBDIR) -ldmumps -lzmumps -lmumps_common -lmpiseq  -lesmumps -lmetis -lpord \
#                                   -lscotch -lscotcherr -lpthread -llapack -lblas

$(EXEC): $(OBJ)
        $(FC) -o $@ $^ -L$(BIBDIR) -ldmumps -lzmumps -lmumps_common -lesmumps -lmetis -lpord \
                                   -lscotch -lscotcherr -lpthread -llapack -lblas

#$(EXEC): $(OBJ)
#       $(FC) -o $@ $^ -L$(BIBDIR) -ldmumps -lzmumps -lmumps_common -lpord \
#                                   -lscotch -lscotcherr -lpthread -llapack -lblas

%.o: %.f90
        $(FC) -o  $@ $(FFLAGS) $?

clean:
        rm -f *.o $(EXEC)
        rm -f *.mod

```

no success with `gfortran` (`/usr/bin/ld: main.o: undefined reference to symbol 'mpi_init_'`)

Any hints?

Thanks

**Comment by gudasergey** [comment]
win32 binary was build using the Intel MKL library. But as I see from your makefile, you don't use it.
Why you don't want to run the prebuild parallel version of fdmnes from 'releases' github section? It is compiled by Intel compiler, powered with Intel MPI and would be faster.

**Comment by carichte** [comment]
Thanks for the response.

The binary from the package or from the releases here give me an immediate segfault.
System: `Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Apart from that, the behavior above should not occur at all: while all CPUs of the system are used, the real runtime actually is longer than in serial processing -- also for "longer" jobs.

**Comment by gudasergey** [comment]
Just now I've tested the binaries on the same platform:
Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Serial and parallel versions work fine.
You compare binaries, build by different compilers with different libraries. Our tests showed, that binaries, build using Intel MKL are 5 times faster.
Can you give me access to your computer ( send to email: gudasergey@gmail.com ) ?

**Comment by carichte** [comment]
I'm  trying to provide access...

**Comment by gudasergey** [comment]
Thank you very much for find of a new bug!
Several years ago I tried to eliminate the dependence from new versions of Glibc. In new ubuntu 18 this sometimes causes the infinite recursion. Today this elimination is not relevant, and I removed it.
The last build contains corrected executables:
[https://github.com/gudasergey/fdmnes/releases/tag/2018_11_30_corrected_build](https://github.com/gudasergey/fdmnes/releases/tag/2018_11_30_corrected_build)
I also copy them to the folder "corrected" on your computer

**Comment by carichte** [comment]
Thanks a lot. I tested it, and it seems to work nicely!
