### ISSUE TITLE
Array out of bounds

### ISSUE THREAD

**Issue by jhein32** [gudasergey/fdmnes#8]
I downloaded the latest source zip from http://neel.cnrs.fr/spip.php?article3137&lang=en this morning (version dated 29th August) and when trying to compile with GCC 8.2 on Linux I get:

```
mpifort -o  fdmx.o -c  -O3  -march=native  fdmx.f90 
fdmx.f90:1036:15:

fdmx.f90:1027:15:

    do iii=1,121
               2
fdmx.f90:1036:15:

       bestelf2(iii,qint) = elfout2(iii)
               1
Warning: Array reference at (1) out of bounds (121 > 120) in loop beginning at (2)
```

I think you want to address this.

**Comment by gudasergey** [comment]
Thank you. The issue was corrected in 2019_09_27 release
